# Generated by Django 4.0.1 on 2022-01-16 07:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questionare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=16)),
                ('lname', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=64)),
                ('phone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^([0-9]){10}', "Hashtag doesn't comply.")])),
                ('course', models.CharField(choices=[('BSc in IT', 'BSc(IT)'), ('BSc in CSc', 'BSc(CS)'), ('BTech in CSc', 'BTech(CS)'), ('BTech in EE', 'BTech(EE)')], max_length=128)),
            ],
        ),
    ]
